### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wzyndul** [wzyndul/sentiment_analysis#9]
- [x] separate youtube_handler
- [x] error handling for youtube API calls
- [x] fix bug with zero division when the are no comments 
- [x] round rating to 2 digits after comma
- [x] scrape miniatures from videos
- [ ] set up google cloud file storage for plots png
- [ ] add logger for errors
